### ISSUE TITLE
$htaFilePath can not be detected, error in script

### ISSUE THREAD

**Issue by JuergenBa** [philjorgensen/Intune#8]
There is an error in your script,

the detection of $htaFilePathis not working.

Join-Path -Path $PSScriptRoot  returns nothing and so hta can not be found.

$lenovoPath = Join-Path -Path $env:ProgramData -ChildPath "Lenovo\ThinkBiosConfig"
**$htaFilePath = Join-Path -Path $PSScriptRoot -ChildPath "ThinkBiosConfig.hta"**
$passFilePath = (Get-ChildItem -Path $PSScriptRoot -Filter "*.ini").FullName

i changed this to

$lenovoPath = Join-Path -Path $env:ProgramData -ChildPath "Lenovo\ThinkBiosConfig"
**$htaFilePath = (Get-ChildItem -Path $PSScriptRoot -Filter "ThinkBiosConfig.hta").FullName**
$passFilePath = (Get-ChildItem -Path $PSScriptRoot -Filter "*.ini").FullName

But the Thinkpad / Windows still asks for an app that should run the .hta file (HTML application host)?

**Comment by philjorgensen** [comment]
This detection is intended to be used with the solution found [here](https://blog.lenovocdrt.com/changing-the-bios-supervisor-password-with-intune-and-the-think-bios-config-tool/#preparing-the-password-file) and has worked ever since. Are you following that blog or using in a different scenario?

**Comment by JuergenBa** [comment]
I followed this blog, 
but the ThinkPad has Visual Studio 2022 installed and so, i get an a pop up windows asking, what application i would like to run for this .hta.

I tried the first solution for changing BIOS settings here (https://blog.lenovocdrt.com/configure-bios-settings-through-intune-using-the-think-bios-config-tool/#create-and-upload-the-win32-app).
But the 2024 version seems to have better logging and diagnostics.

But even your script fails here .. you need to pass the key value with the ini file...!

$arguments = "`"file=$passFilePath`" `"pass=$secretKey`" `"log=$lenovoPath`""

It must be

$arguments = "`"file=$passFilePath`" `"key=$secretKey`" `"log=$lenovoPath`""

**Comment by philjorgensen** [comment]
Sorry, but this has worked for a long time. The tool accepts both the **key** and **pass** parameters so that change is irrelevant.

**Comment by JuergenBa** [comment]
Any idea, how i can run mshta.exe with the correct parameters?
I always get the ThinkBiosConfig.hta Windows, but parameters are not accepted.

Start-Process cmd.exe -ArgumentList "/C $mshtaFileExecutable $htaFilePath $arg $log" -NoNewWindow -Wait

C:\WINDOWS\System32\mshta.exe C:\tmp\ThinkBiosConfig.hta "file=c:\tmp\ThinkBiosConfigOn.ini" "key=*********" "log=%ProgramData%\Lenovo\ThinkBiosConfig\"

ThinkBiosConfig.hta -help should show more information, but it only shows some release notes.

**Comment by philjorgensen** [comment]
What version of the tool are you testing with and are you testing in System context with psexec?

**Comment by JuergenBa** [comment]
I uses tbct144 and i test this on a ThinkPad with Powershell ISE and cmd prompt.
After some trail and errors, i have a working setup for testing.

i call mshta.exe now like this

Start-Process cmd.exe -ArgumentList "/c $cmd" -NoNewWindow -Wait

$cmd = ' "C:\WINDOWS\System32\mshta.exe" "C:\tmp\ThinkBiosConfig.hta" "file=c:\tmp\ThinkBiosConfigOn.ini" "key=*********" "log=%ProgramData%\Lenovo\ThinkBiosConfig"'

Deployment is done with intune like described in your blog. But this fails, as soon as more than one .hta application is installed or Visual Studio 2022 breaks the default .hta app.

I think Lenovo has no better solution for settings BIOS through intune right now.

**Comment by philjorgensen** [comment]
> I think Lenovo has no better solution for settings BIOS through intune right now.

Currently, not at the moment. There's a PowerShell version of the tool in development that should be released later this year and another solution (Lenovo Device Manager) for Intune integration in the works as well.

Ideally, have the BIOS settings configured in the factory before drop-ship.

**Comment by philjorgensen** [comment]
@JuergenBa 

After further investigation, something happened between now and initial release of the script and how parameters are parsed with cmd.exe. I updated the code to use mshta.exe directly and it works now.

Please give it a try and let me know if that works on your end as well.

**Comment by JuergenBa** [comment]
Thanks, i tried to use your new script, but i still have problem with Intune Deployment.
Sometimes it shows up and sometimes not.

I was able to use your original script with a few modifications for debugging (transcript, writing to tmp foleder). 
But my Test Thinkpad has no Visual Studio installed at all (and still fails intune).
The Thinkpad was installed with Windows 11 from scratch and here this works.

I will check with the new script/method and report in a few days.

**Comment by philjorgensen** [comment]
I just verified this works on a different model in my lab this morning.
